; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

define i1 @cmp_sext_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_sext_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    ADI 128
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    ADI 128
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    MOV D, A
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB L
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    RET
entry:
  %sa = sext i8 %a to i16
  %sb = sext i8 %b to i16
  %cmp = icmp slt i16 %sa, %sb
  ret i1 %cmp
}

define i1 @cmp_zext_i8(i8 %a, i8 %b) {
; CHECK-LABEL: cmp_zext_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV E, A
; CHECK-NEXT:    MVI D, 0
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    RET
entry:
  %za = zext i8 %a to i16
  %zb = zext i8 %b to i16
  %cmp = icmp ult i16 %za, %zb
  ret i1 %cmp
}

define i1 @cmp_mixed_i16(i16 %a, i16 %b) {
; CHECK-LABEL: cmp_mixed_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    ADI 128
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    INX H
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB L
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    RET
entry:
  %tr = trunc i16 %a to i8
  %se = sext i8 %tr to i16
  %cmp = icmp sgt i16 %se, %b
  ret i1 %cmp
}
