; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 -verify-machineinstrs | FileCheck %s

; Pointer compares should lower without leaving compare/branch pseudos.

define i8 @ptr_eq(ptr %a, ptr %b) {
; CHECK-LABEL: ptr_eq:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    XRA C
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRA B
; CHECK-NEXT:    ORA H
; CHECK-NEXT:    SUI 1
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    RET
entry:
  %cmp = icmp eq ptr %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}

define i8 @ptr_ult(ptr %a, ptr %b) {
; CHECK-LABEL: ptr_ult:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    RET
entry:
  %cmp = icmp ult ptr %a, %b
  %z = zext i1 %cmp to i8
  ret i8 %z
}
