; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 | FileCheck %s

; Select with constant operands.
; Adapted from RISC-V select-const.ll

define i16 @select_const_one_zero(i1 %cond) {
; CHECK-LABEL: select_const_one_zero:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV A, M
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MVI B, 0
; CHECK-NEXT:    LXI D, 1
; CHECK-NEXT:    ANA E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANA D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    RET
entry:
  %sel = select i1 %cond, i16 1, i16 0
  ret i16 %sel
}

define i16 @select_const_one_away(i1 %cond) {
; CHECK-LABEL: select_const_one_away:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    LXI D, 4
; CHECK-NEXT:    LXI B, 3
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    RNZ
; CHECK-NEXT:  LBB1_1: ; %entry
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    RET
entry:
  %sel = select i1 %cond, i16 3, i16 4
  ret i16 %sel
}

define i16 @select_const_arbitrary(i1 %cond) {
; CHECK-LABEL: select_const_arbitrary:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    LXI D, 1000
; CHECK-NEXT:    LXI B, 42
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    RNZ
; CHECK-NEXT:  LBB2_1: ; %entry
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    RET
entry:
  %sel = select i1 %cond, i16 42, i16 1000
  ret i16 %sel
}

define i8 @select_const_i8(i1 %cond) {
; CHECK-LABEL: select_const_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB3_1
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    MVI A, 20
; CHECK-NEXT:    RET
; CHECK-NEXT:  LBB3_1:
; CHECK-NEXT:    MVI A, 10
; CHECK-NEXT:    RET
entry:
  %sel = select i1 %cond, i8 10, i8 20
  ret i8 %sel
}

define i16 @select_const_zero_nonzero(i1 %cond) {
; CHECK-LABEL: select_const_zero_nonzero:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    LXI D, 255
; CHECK-NEXT:    LXI B, 0
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    RNZ
; CHECK-NEXT:  LBB4_1: ; %entry
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    RET
entry:
  %sel = select i1 %cond, i16 0, i16 255
  ret i16 %sel
}
