; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mattr=i8085,sram < %s -march=i8085 | FileCheck %s

; Ternary/conditional expression patterns: min, max, abs, clamp.
; Adapted from RISC-V select-const.ll and select-binop-identity.ll

; min(a, b) signed
define i16 @min_i16(i16 %a, i16 %b) {
; CHECK-LABEL: min_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB L
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    RNZ
; CHECK-NEXT:  LBB0_1: ; %entry
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    RET
entry:
  %cmp = icmp slt i16 %a, %b
  %r = select i1 %cmp, i16 %a, i16 %b
  ret i16 %r
}

; max(a, b) signed
define i16 @max_i16(i16 %a, i16 %b) {
; CHECK-LABEL: max_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB L
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    RNZ
; CHECK-NEXT:  LBB1_1: ; %entry
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    RET
entry:
  %cmp = icmp sgt i16 %a, %b
  %r = select i1 %cmp, i16 %a, i16 %b
  ret i16 %r
}

; abs(a) = (a < 0) ? -a : a
define i16 @abs_i16(i16 %a) {
; CHECK-LABEL: abs_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    RP
; CHECK-NEXT:  LBB2_1: ; %select.true.sink
; CHECK-NEXT:    LXI D, 0
; CHECK-NEXT:    MOV A, E
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    SBB B
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:  ; %bb.2: ; %select.end
; CHECK-NEXT:    RET
entry:
  %cmp = icmp slt i16 %a, 0
  %neg = sub i16 0, %a
  %r = select i1 %cmp, i16 %neg, i16 %a
  ret i16 %r
}

; Conditional add: (cond ? a+b : a)
define i16 @cond_add(i16 %a, i16 %b, i1 %cond) {
; CHECK-LABEL: cond_add:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV H, M
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    RZ
; CHECK-NEXT:  LBB3_1:
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    ADD E
; CHECK-NEXT:    MOV C, A
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    ADC D
; CHECK-NEXT:    MOV B, A
; CHECK-NEXT:  ; %bb.2: ; %entry
; CHECK-NEXT:    RET
entry:
  %sum = add i16 %a, %b
  %r = select i1 %cond, i16 %sum, i16 %a
  ret i16 %r
}

; Unsigned min for i8
define i8 @umin_i8(i8 %a, i8 %b) {
; CHECK-LABEL: umin_i8:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 3
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    DCX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    SUB C
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB4_2
; CHECK-NEXT:  ; %bb.1: ; %entry
; CHECK-NEXT:    MOV B, C
; CHECK-NEXT:  LBB4_2: ; %entry
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    RET
entry:
  %cmp = icmp ult i8 %a, %b
  %r = select i1 %cmp, i8 %a, i8 %b
  ret i8 %r
}

; clamp(x, lo, hi) = min(max(x, lo), hi)
define i16 @clamp_i16(i16 %x, i16 %lo, i16 %hi) {
; CHECK-LABEL: clamp_i16:
; CHECK:         .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    LXI H, 2
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV E, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV D, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB L
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    JNZ LBB5_1
; CHECK-NEXT:  ; %bb.4: ; %entry
; CHECK-NEXT:    MOV D, B
; CHECK-NEXT:    MOV E, C
; CHECK-NEXT:  LBB5_1: ; %entry
; CHECK-NEXT:    LXI H, 6
; CHECK-NEXT:    DAD SP
; CHECK-NEXT:    MOV C, M
; CHECK-NEXT:    INX H
; CHECK-NEXT:    MOV B, M
; CHECK-NEXT:    MOV A, B
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV H, A
; CHECK-NEXT:    MOV A, D
; CHECK-NEXT:    XRI 128
; CHECK-NEXT:    MOV L, A
; CHECK-NEXT:    MOV A, C
; CHECK-NEXT:    SUB E
; CHECK-NEXT:    MOV A, H
; CHECK-NEXT:    SBB L
; CHECK-NEXT:    SBB A
; CHECK-NEXT:    ANI 1
; CHECK-NEXT:    ORA A
; CHECK-NEXT:    RNZ
; CHECK-NEXT:  LBB5_2: ; %entry
; CHECK-NEXT:    MOV B, D
; CHECK-NEXT:    MOV C, E
; CHECK-NEXT:  ; %bb.3: ; %entry
; CHECK-NEXT:    RET
entry:
  %cmp1 = icmp slt i16 %x, %lo
  %mid = select i1 %cmp1, i16 %lo, i16 %x
  %cmp2 = icmp sgt i16 %mid, %hi
  %r = select i1 %cmp2, i16 %hi, i16 %mid
  ret i16 %r
}
